### ISSUE TITLE
What version of Celery is supported?

### ISSUE THREAD

**Issue by ezheidtmann** [3stack-software/celery-cloudwatch#10]
Looks like 3.1, also 4?

**Comment by nathan-muir** [comment]
I haven't tested with 4.

It seems like there might be some changes - [with support for multiple events](http://docs.celeryproject.org/en/latest/internals/protocol.html#event-messages).

**Comment by ezheidtmann** [comment]
Thanks! It would be cool to have that info in the README (I wasn't able to find it there or in a `requirements.txt` or `setup.py` or anything else)
